/****** Object:  Table [dbo].[DBLog]    Script Date: 24/06/2025 19:29:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DBLog](
	[DBLogId] [int] IDENTITY(1,1) NOT NULL,
	[Message] [nvarchar](max) NULL,
	[Status] [nvarchar](256) NOT NULL,
	[TS] [datetime] NOT NULL,
 CONSTRAINT [PK_DBLog] PRIMARY KEY CLUSTERED 
(
	[DBLogId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[DBLog] ADD  DEFAULT (getdate()) FOR [TS]
GO
