USE [VideoPlayerDebug]
GO
/****** Object:  Table [dbo].[VideoActor]    Script Date: 24/06/2025 21:17:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VideoActor](
	[VideoId] [int] NOT NULL,
	[ActorId] [int] NOT NULL,
 CONSTRAINT [PK_VideoActor] PRIMARY KEY CLUSTERED 
(
	[VideoId] ASC,
	[ActorId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
