USE [VideoPlayerDebug]
GO
/****** Object:  Table [dbo].[DBLogError]    Script Date: 24/06/2025 21:17:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DBLogError](
	[DBLogErrorId] [int] IDENTITY(1,1) NOT NULL,
	[Message] [nvarchar](max) NULL,
	[Status] [nvarchar](256) NOT NULL,
	[TS] [datetime] NOT NULL,
 CONSTRAINT [PK_DBLogError] PRIMARY KEY CLUSTERED 
(
	[DBLogErrorId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[DBLogError] ADD  DEFAULT (getdate()) FOR [TS]
GO
