USE [master]
GO
/****** Object:  Database [VideoPlayerDebug]    Script Date: 24/06/2025 21:17:59 ******/
CREATE DATABASE [VideoPlayerDebug]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'VideoPlayerDebug', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLDEV\MSSQL\DATA\VideoPlayerDebug.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'VideoPlayerDebug_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLDEV\MSSQL\DATA\VideoPlayerDebug_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [VideoPlayerDebug] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [VideoPlayerDebug].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [VideoPlayerDebug] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [VideoPlayerDebug] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [VideoPlayerDebug] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [VideoPlayerDebug] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [VideoPlayerDebug] SET ARITHABORT OFF 
GO
ALTER DATABASE [VideoPlayerDebug] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [VideoPlayerDebug] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [VideoPlayerDebug] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [VideoPlayerDebug] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [VideoPlayerDebug] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [VideoPlayerDebug] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [VideoPlayerDebug] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [VideoPlayerDebug] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [VideoPlayerDebug] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [VideoPlayerDebug] SET  DISABLE_BROKER 
GO
ALTER DATABASE [VideoPlayerDebug] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [VideoPlayerDebug] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [VideoPlayerDebug] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [VideoPlayerDebug] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [VideoPlayerDebug] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [VideoPlayerDebug] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [VideoPlayerDebug] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [VideoPlayerDebug] SET RECOVERY FULL 
GO
ALTER DATABASE [VideoPlayerDebug] SET  MULTI_USER 
GO
ALTER DATABASE [VideoPlayerDebug] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [VideoPlayerDebug] SET DB_CHAINING OFF 
GO
ALTER DATABASE [VideoPlayerDebug] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [VideoPlayerDebug] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [VideoPlayerDebug] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [VideoPlayerDebug] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'VideoPlayerDebug', N'ON'
GO
ALTER DATABASE [VideoPlayerDebug] SET QUERY_STORE = OFF
GO
ALTER DATABASE [VideoPlayerDebug] SET  READ_WRITE 
GO
